recipes:
  # Whether to generate Flawed and Chipped Gems for materials and recipes involving them.
  # Useful for mods like TerraFirmaCraft.
  # Default: false
  generateLowQualityGems: true

  # Whether to remove Block/Ingot compression and decompression in the Crafting Table.
  # Default: false
  disableManualCompression: true

  # Change the recipe of Rods in the Lathe to 1 Rod and 2 Small Piles of Dust, instead of 2 Rods.
  # Default: false
  harderRods: false

  # Whether to make crafting recipes for Bricks, Firebricks, and Coke Bricks harder.
  # Default: false
  harderBrickRecipes: false

  # Whether to nerf Wood crafting to 2 Planks from 1 Log, and 2 Sticks from 2 Planks.
  # Default: false
  nerfWoodCrafting: false

  # Whether to make Wood related recipes harder.
  # Excludes sticks and planks.
  # Default: false
  hardWoodRecipes: false

  # Recipes for Buckets, Cauldrons, Hoppers, and Iron Bars require Iron Plates, Rods, and more.
  # Default: true
  hardIronRecipes: true

  # Whether to make Redstone related recipes harder.
  # Default: false
  hardRedstoneRecipes: false

  # Whether to make Vanilla Tools and Armor recipes harder.
  # Excludes Flint and Steel, and Buckets.
  # Default: false
  hardToolArmorRecipes: false

  # Whether to make miscellaneous recipes harder.
  # Default: false
  hardMiscRecipes: false

  # Whether to make Glass related recipes harder. Default: true
  hardGlassRecipes: true

  # Whether to nerf the Paper crafting recipe.
  # Default: true
  nerfPaperCrafting: true

  # Recipes for items like Iron Doors, Trapdoors, Anvil require Iron Plates, Rods, and more.
  # Default: false
  hardAdvancedIronRecipes: false

  # Whether to make coloring blocks like Concrete or Glass harder.
  # Default: false
  hardDyeRecipes: false

  # Whether to remove charcoal smelting recipes from the vanilla furnace.
  # Default: true
  harderCharcoalRecipe: true

  # Whether to make the Flint and Steel recipe require steel parts.
  # Default: true.
  flintAndSteelRequireSteel: true

  # Whether to remove Vanilla Block Recipes from the Crafting Table.
  # Default: false
  removeVanillaBlockRecipes: false

worldgen:
  # Should all Stone Types drop unique Ore Item Blocks?
  # Default: false (meaning only Stone, Netherrack, and Endstone)
  allUniqueStoneTypes: false

  # Should Sand-like ores fall?
  # This includes gravel, sand, and red sand ores.
  # Default: false (no falling ores)
  sandOresFall: false

  # Debug ore vein placement? (will print placed veins to server's debug.log)
  # Default: false (no placement printout in debug.log)
  debugWorldgen: false

machines:
  # Whether to require a Wrench, Wirecutter, or other GregTech tools to break machines, casings, wires, and more.
  # Default: false
  requireGTToolsForBlocks: false

  # Whether machines explode in rainy weather or when placed next to certain terrain, such as fire or lava
  # Default: false
  doTerrainExplosion: false

  # Whether machines or boilers damage the terrain when they explode.
  # Note machines and boilers always explode when overloaded with power or met with special conditions, regardless of this config.
  # Default: true
  doesExplosionDamagesTerrain: false

  # Divisor for Recipe Duration per Overclock.
  # Default: 2.0
  overclockDivisor: 2.0

  # Whether to play machine sounds while machines are active.
  # Default: true
  machineSounds: true

  # Whether Steam Multiblocks should use Steel instead of Bronze.
  # Default: false
  steelSteamMultiblocks: false

client:
  # Whether or not to enable Emissive Textures for GregTech Machines.
  # Default: true
  machinesEmissiveTextures: true

