# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				dolphin = true
				item = true
				potion = true
				chicken = true
				cow = true
				slime = true
				pig = true
				item_frame = true
				skeleton = true
				phantom = true
				bat = true
				zombie = true
				cod = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				drowned = true
				spider = true
				parrot = true
				creeper = true
				sheep = true
				lightning_bolt = true
				player = true
				enderman = true

			[light_sources.settings.entities.botania]
				mana_burst = true
				flame_ring = true

			[light_sources.settings.entities.powah]
				charged_snowball = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				dripstone_creeper = true
				cave_creeper = true

			[light_sources.settings.entities.ad_astra]
				tier_1_rover = true

